stages:
  - test
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"
  UV_VERSION: 0.6.8
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy
  PYTHON_VERSION: "3.13"

.rules_mrs_and_protected:
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  - if: $CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
  - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.dev_dependency_job: &dev_dependency_job
  image: "ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-${BASE_LAYER}"
  cache:
    key: devdependencies-${PYTHON_VERSION}
    paths:
      - .cache/pip/
      - .cache/poetry/
      - .venv/

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.4.0
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        when: never
      - if: $CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.4.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.4.0


test:lib:
  <<: *dev_dependency_job
  rules:
    - !reference [.rules_mrs_and_protected]
  stage: test
  needs: []
  parallel:
    matrix:
      - PYTHON_VERSION: "3.13"
        TOX_SKIP_ENV: "^(?!py313)"
  script:
    - uvx tox
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
